name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node.js
        uses: omeryttnc/SchoolProjectAPI_typescript@main
        with:
          node-version: '16'  # or the version you need

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
