on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu

    steps:
    - name: install npm
      run: |
        npm install
        npm run startNodeman
    
