on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
    - name: install npm
      uses: actions/checkout@v2
      with:
        path: SchoolProjectAPI_typescript
        run: |
          npm install
          npm run startNodeman
  
