on:
  push:
    branches:
      - main

jobs:
  run_pull:
    name: run pull
    runs-on: ubuntu-latest
    steps:
    - name: install npm
      run: |
          cd ..
    - name: install
      run: |
        npm install
  
